apiVersion: v1
kind: Namespace
metadata:
  name: ocp-48-cluster-k
  labels:
    name: ocp-48-cluster-k
---
apiVersion: v1
kind: Namespace
metadata:
  name: common
  labels:
    name: common
---
apiVersion: v1
kind: Namespace
metadata:
  name: clusters-sub 
  labels:
    name: clusters-sub
---
apiVersion: v1
kind: Namespace
metadata:
  name: policies-sub
  labels:
    name: policies-sub
    