apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: openshift-gitops
spec: 
  destination:
    server: https://kubernetes.default.svc
    namespace: ocp-48-cluster-k 
  project: default
  source:
    path: clusters/ocp-48-cluster-k.cp.fyre.ibm.com/ztp/siteconfig
    repoURL: https://github.com/traghave123/telco-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true