apiVersion: v1
kind: Namespace
metadata:
  name: ocp-48-cluster-k
  labels:
    name: ocp-48-cluster-k
---
apiVersion: v1
kind: Namespace
metadata:
  name: common
  labels:
    name: common
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: common-default-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: common